# Generated by Django 5.2 on 2025-10-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postproduit',
            name='devise',
            field=models.CharField(default='$', max_length=10),
        ),
    ]
