# Generated by Django 5.2 on 2025-10-15 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0002_postproduit_devise'),
        ('blog', '0032_catalogue_devise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reabilitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('planifier_depuis', models.DateField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('budget', models.FloatField()),
                ('devise', models.CharField(default='$', max_length=50)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reabilitations', to='blog.blog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reabilitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
