# Generated by Django 5.2 on 2025-07-21 09:45

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostMaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(blank=True, default='RDC', max_length=25)),
                ('ville', models.CharField(blank=True, default='kinshasa', max_length=25)),
                ('commune', models.CharField(blank=True, max_length=25)),
                ('type_bien', models.CharField(blank=True, max_length=25, null=True)),
                ('nombre_chambre', models.IntegerField(blank=True, null=True)),
                ('nombre_piece', models.IntegerField(blank=True, null=True)),
                ('nombre_douche', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('has_balcony', models.BooleanField(blank=True, null=True)),
                ('has_terasse', models.BooleanField(blank=True, null=True)),
                ('has_parking', models.BooleanField(blank=True, null=True)),
                ('maisons_meuble', models.BooleanField(blank=True, null=True)),
                ('cuisine_meuble', models.BooleanField(blank=True, null=True)),
                ('cuisine', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageMaisons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.BaseImage.upload_to_unique_uuid)),
                ('post_maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immobilier.postmaison')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
