# Generated by Django 5.2 on 2025-09-09 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_reservation_imagereservation'),
        ('immobilier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmaison',
            name='commune',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='postmaison',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='SaveProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_bien', models.CharField(blank=True, max_length=25, null=True)),
                ('commune', models.CharField(blank=True, max_length=25, null=True)),
                ('quartier', models.CharField(blank=True, max_length=25, null=True)),
                ('rue', models.CharField(blank=True, max_length=25, null=True)),
                ('numero', models.CharField(blank=True, max_length=25, null=True)),
                ('ville', models.CharField(blank=True, max_length=25, null=True)),
                ('pays', models.CharField(blank=True, max_length=25, null=True)),
                ('statut', models.CharField(blank=True, max_length=25, null=True)),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('devise_payement', models.CharField(blank=True, default='$', max_length=25)),
                ('id_maison', models.CharField(blank=True, max_length=25, null=True)),
                ('nom_complet_occupant', models.CharField(blank=True, max_length=255, null=True)),
                ('tel_occupant', models.CharField(blank=True, max_length=25, null=True)),
                ('date_entrer', models.DateField(blank=True, null=True)),
                ('garantie', models.IntegerField(blank=True, null=True)),
                ('devise_garantie', models.CharField(blank=True, default='$', max_length=25)),
                ('contratBail', models.FileField(blank=True, null=True, upload_to='document/')),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='blog.blog')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
