# Generated by Django 5.2 on 2025-09-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0002_alter_postmaison_commune_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveproperty',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='saveproperty',
            name='ville',
        ),
        migrations.AddField(
            model_name='saveproperty',
            name='mail_occupant',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
