# Generated by Django 5.2 on 2025-09-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0003_remove_saveproperty_pays_remove_saveproperty_ville_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveproperty',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='saveproperty',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='saveproperty',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='saveproperty',
            name='quartier',
        ),
        migrations.RemoveField(
            model_name='saveproperty',
            name='rue',
        ),
        migrations.AddField(
            model_name='saveproperty',
            name='adresse',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
