# Generated by Django 5.2 on 2025-09-26 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0004_remove_saveproperty_blog_remove_saveproperty_commune_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('date_payement', models.DateField()),
                ('mois', models.CharField(max_length=50)),
                ('oberservation', models.CharField(blank=True, default='totalite', max_length=50)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='immobilier.saveproperty')),
            ],
        ),
    ]
