# Generated by Django 5.2 on 2025-10-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0005_loyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyer',
            name='oberservation',
        ),
        migrations.AddField(
            model_name='loyer',
            name='observation',
            field=models.CharField(blank=True, default='totalite', max_length=50),
        ),
    ]
