# Generated by Django 5.2 on 2025-10-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0006_remove_loyer_oberservation_loyer_observation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loyer',
            options={'ordering': ['-annee', 'mois']},
        ),
        migrations.AddField(
            model_name='loyer',
            name='ancre_hedera',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='loyer',
            name='annee',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='loyer',
            name='hash_document',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='loyer',
            name='lien_document',
            field=models.FileField(blank=True, null=True, upload_to='immobilier/recus/'),
        ),
        migrations.AddField(
            model_name='loyer',
            name='tp_hedera',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='loyer',
            name='mois',
            field=models.IntegerField(default=1),
        ),
    ]
