# Generated by Django 5.2 on 2025-11-01 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0007_alter_loyer_options_loyer_ancre_hedera_loyer_annee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_document', models.FileField(help_text='Lien vers le fichier PDF généré de la quittance.', upload_to='quittances/%Y/%m/', verbose_name='Fichier Quittance PDF')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant Payé')),
                ('mois_concerne', models.CharField(max_length=50, verbose_name='Mois et Année Concernés')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quittances_emises', to=settings.AUTH_USER_MODEL, verbose_name='Bailleur / Émetteur')),
            ],
            options={
                'verbose_name': 'Document (Quittance)',
                'verbose_name_plural': 'Documents (Quittances)',
                'ordering': ['-cree_le'],
            },
        ),
    ]
