# Generated by Django 5.2 on 2025-11-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0008_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyer',
            name='lien_document',
        ),
        migrations.AddField(
            model_name='loyer',
            name='url_document',
            field=models.FileField(blank=True, help_text='Lien vers le fichier PDF généré de la quittance.', null=True, upload_to='quittances/%Y/%m/', verbose_name='Fichier Quittance PDF'),
        ),
    ]
