# Generated by Django 5.2.7 on 2025-11-03 20:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0009_remove_loyer_lien_document_loyer_url_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyer',
            name='qr_document',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.BaseImage.upload_to_unique_uuid),
        ),
        migrations.AddField(
            model_name='loyer',
            name='signer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loyer',
            name='hash_document',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
