# Generated by Django 5.2.7 on 2025-11-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0010_loyer_qr_document_loyer_signer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyer',
            name='code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
