# Generated by Django 5.2.7 on 2025-11-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0011_loyer_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyer',
            name='hash_document',
        ),
        migrations.AddField(
            model_name='loyer',
            name='sequence_number_hedera',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
