# Generated by Django 5.2.7 on 2025-11-12 12:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0012_remove_loyer_hash_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loyer',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 1, 12, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loyer',
            name='document_hash_sha256',
            field=models.CharField(blank=True, default='PEDING', max_length=64, verbose_name='Hash SHA-256 (Ancrage)'),
        ),
        migrations.AddField(
            model_name='loyer',
            name='hedera_timestamp',
            field=models.CharField(blank=True, default='PEDING', max_length=255, verbose_name='Horodatage Hedera (Consensus Time)'),
        ),
        migrations.AddField(
            model_name='loyer',
            name='hedera_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de Transaction Hedera'),
        ),
        migrations.AddField(
            model_name='loyer',
            name='lien_verification_hedera',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien de Vérification Hedera'),
        ),
        migrations.AddField(
            model_name='loyer',
            name='signataire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quittance_signes', to=settings.AUTH_USER_MODEL, verbose_name='Signataire'),
        ),
        migrations.AddField(
            model_name='loyer',
            name='statut',
            field=models.CharField(default='SIGNÉ & ANCRÉ', max_length=50, verbose_name='Statut du Document'),
        ),
        migrations.AddField(
            model_name='loyer',
            name='type_document',
            field=models.CharField(blank=True, default='quittance', max_length=100, verbose_name='Type de Document'),
        ),
        migrations.AlterField(
            model_name='loyer',
            name='code',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
