# Generated by Django 5.2.7 on 2025-11-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0013_loyer_date_creation_loyer_document_hash_sha256_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyer',
            name='ancre_hedera',
        ),
        migrations.RemoveField(
            model_name='loyer',
            name='sequence_number_hedera',
        ),
        migrations.RemoveField(
            model_name='loyer',
            name='tp_hedera',
        ),
    ]
