# Generated by Django 5.2.7 on 2025-11-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0014_remove_loyer_ancre_hedera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyer',
            name='document_hash_sha256',
            field=models.CharField(blank=True, default='PENDING', max_length=64, verbose_name='Hash SHA-256 (Ancrage)'),
        ),
        migrations.AlterField(
            model_name='loyer',
            name='hedera_timestamp',
            field=models.CharField(blank=True, default='PENDING', max_length=255, verbose_name='Horodatage Hedera (Consensus Time)'),
        ),
        migrations.AlterField(
            model_name='loyer',
            name='statut',
            field=models.CharField(default='', max_length=50, verbose_name='Statut du Document'),
        ),
    ]
