# Generated by Django 5.2 on 2025-07-21 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepenseSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date_depense', models.DateField(blank=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('mode_paiement', models.CharField(blank=True, max_length=25, null=True)),
                ('categorie', models.CharField(blank=True, max_length=25, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depense_salon', to='blog.blog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployerSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('family_name', models.CharField(blank=True, max_length=25, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('commune', models.CharField(blank=True, max_length=25, null=True)),
                ('rue', models.CharField(blank=True, max_length=25, null=True)),
                ('numero_rue', models.CharField(blank=True, max_length=15, null=True)),
                ('fonction', models.CharField(blank=True, max_length=25, null=True)),
                ('sexe', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_salon', to='blog.blog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emploi_salon', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HoraireEmployerSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaire_employer_salon', to='blog.blog')),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horaire', to='salon.employersalon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevenusSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField()),
                ('categorie', models.CharField(blank=True, max_length=25, null=True)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalaireSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('devise', models.CharField(max_length=20)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaire_salon', to='blog.blog')),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaire_salon', to='salon.employersalon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_article', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('unite', models.CharField(blank=True, max_length=20, null=True)),
                ('seuil_alert', models.IntegerField(blank=True, null=True)),
                ('modify_at', models.DateField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_salon', to='blog.blog')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
