# Generated by Django 5.2 on 2025-07-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employersalon',
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='employersalon',
            name='user',
        ),
        migrations.RemoveField(
            model_name='horaireemployersalon',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='salairesalon',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='horaireemployersalon',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='revenussalon',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='salairesalon',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='stocksalon',
            name='blog',
        ),
        migrations.DeleteModel(
            name='DepenseSalon',
        ),
        migrations.DeleteModel(
            name='EmployerSalon',
        ),
        migrations.DeleteModel(
            name='HoraireEmployerSalon',
        ),
        migrations.DeleteModel(
            name='RevenusSalon',
        ),
        migrations.DeleteModel(
            name='SalaireSalon',
        ),
        migrations.DeleteModel(
            name='StockSalon',
        ),
    ]
