# Generated by Django 5.2 on 2025-07-21 09:45

import blog.models
import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type_page', models.CharField(max_length=25)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('note', models.IntegerField(blank=True, default=0)),
                ('nombre_avis', models.IntegerField(blank=True, default=0)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='actif')),
            ],
        ),
        migrations.CreateModel(
            name='ImageProfilBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=core.models.BaseImage.upload_to_unique_uuid)),
                ('video', models.FileField(null=True, upload_to=blog.models.upload_to_unique_uuid)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_telephone', models.CharField(blank=True, max_length=25, null=True)),
                ('longetude', models.IntegerField(blank=True, null=True)),
                ('latitude', models.IntegerField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=30, null=True)),
                ('pays', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi', models.BooleanField(blank=True, default=False)),
                ('service_traiteur', models.BooleanField(blank=True, default=False)),
                ('livraison', models.BooleanField(blank=True, default=False)),
                ('parking', models.BooleanField(blank=True, default=False)),
                ('evenement', models.BooleanField(blank=True, default=False)),
                ('service_domicile', models.BooleanField(blank=True, default=False)),
                ('emporter', models.BooleanField(blank=True, default=False)),
                ('manucure_pedicure', models.BooleanField(blank=True, default=False)),
                ('maquillage', models.BooleanField(blank=True, default=False)),
                ('coifure_evenement', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BlogAdministrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_admin', models.IntegerField()),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='blog.blog')),
            ],
        ),
    ]
