# Generated by Django 5.2 on 2025-07-21 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogadministrateur',
            name='user',
            field=models.ManyToManyField(related_name='blog', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imageprofilblog',
            name='blog',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='blog.blog'),
        ),
        migrations.AddField(
            model_name='profileblog',
            name='blog',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil', to='blog.blog'),
        ),
        migrations.AddField(
            model_name='service',
            name='blog',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='blog.blog'),
        ),
    ]
