# Generated by Django 5.2 on 2025-07-24 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='vente_article',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('family_name', models.CharField(blank=True, max_length=25, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('commune', models.CharField(blank=True, max_length=25, null=True)),
                ('rue', models.CharField(blank=True, max_length=25, null=True)),
                ('numero_rue', models.CharField(blank=True, max_length=15, null=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('fonction', models.CharField(blank=True, max_length=25, null=True)),
                ('sexe', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('telephone', models.CharField(blank=True, max_length=25, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
