# Generated by Django 5.2 on 2025-08-06 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_service_vente_article_employer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=800, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_reservation', models.DateTimeField()),
                ('status', models.CharField(blank=True, default='attent', max_length=50)),
                ('qr_resevation', models.ImageField(blank=True, null=True, upload_to='image_qr')),
                ('montant_total', models.IntegerField(blank=True, null=True)),
                ('montant_requis', models.IntegerField(blank=True, null=True)),
                ('montant_verser', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('from_blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_from_blog', to='blog.blog')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_reservation', to=settings.AUTH_USER_MODEL)),
                ('to_blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_blog', to='blog.blog')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
