# Generated by Django 5.2 on 2025-08-06 19:32

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='qr_resevation',
            field=models.ImageField(blank=True, null=True, upload_to='image_qr/'),
        ),
        migrations.CreateModel(
            name='ImageReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=core.models.BaseImage.upload_to_unique_uuid)),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.reservation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
