# Generated by Django 5.2 on 2025-08-08 14:31

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_reservation_qr_resevation_imagereservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('devise', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='employer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='from_blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_from_blog', to='blog.blog'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='qr_resevation',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.BaseImage.upload_to_unique_uuid),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='to_blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_blog', to='blog.blog'),
        ),
    ]
