# Generated by Django 5.2 on 2025-08-08 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_salaire_employer_name_alter_reservation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
    ]
