# Generated by Django 5.2 on 2025-08-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_employer_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='family_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
