# Generated by Django 5.2 on 2025-08-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_reservation_family_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='nombre_personne',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
