# Generated by Django 5.2 on 2025-08-09 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_reservation_nombre_personne'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='to_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='from_blog',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='to_blog',
        ),
        migrations.AddField(
            model_name='reservation',
            name='From',
            field=models.CharField(blank=True, default='blog', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='blog.blog'),
        ),
    ]
