# Generated by Django 5.2 on 2025-08-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_to_user_reservation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='devise',
            field=models.CharField(blank=True, default='$', max_length=15),
        ),
    ]
