# Generated by Django 5.2 on 2025-09-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_reservation_devise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='family_name',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='numero_rue',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='rue',
        ),
        migrations.AddField(
            model_name='employer',
            name='adresse',
            field=models.CharField(blank=True, db_default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
