# Generated by Django 5.2 on 2025-09-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_employer_commune_remove_employer_family_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='devise',
            field=models.CharField(blank=True, db_default='$', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
