# Generated by Django 5.2 on 2025-09-07 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_horaire_delete_salaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaire',
            name='blog',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
    ]
