# Generated by Django 5.2 on 2025-09-07 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_horaire_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.DeleteModel(
            name='ImageReservation',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
