# Generated by Django 5.2 on 2025-09-07 23:27

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_reservation_blog_remove_reservation_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1500, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_reservation', models.DateTimeField()),
                ('status', models.CharField(blank=True, default='Attente', max_length=50)),
                ('message', models.CharField(blank=True, max_length=1500, null=True)),
                ('qr_resevation', models.ImageField(blank=True, null=True, upload_to=core.models.BaseImage.upload_to_unique_uuid)),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('nbr_personne', models.IntegerField(blank=True, null=True)),
                ('From', models.CharField(blank=True, default='blog', max_length=10)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('type_montant', models.CharField(blank=True, default='verser', max_length=10, null=True)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='blog.blog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=core.models.BaseImage.upload_to_unique_uuid)),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.reservation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
