# Generated by Django 5.2 on 2025-09-09 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_reservation_imagereservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date_depense', models.DateField(blank=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Revenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('date_revenu', models.DateField()),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_article', models.CharField(max_length=255)),
                ('categorie', models.CharField(blank=True, max_length=500, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('unite', models.CharField(blank=True, max_length=20, null=True)),
                ('seuil_alert', models.IntegerField(blank=True, null=True)),
                ('modify_at', models.DateField(auto_now=True)),
                ('prixAchat', models.IntegerField(blank=True, null=True)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
        ),
    ]
