# Generated by Django 5.2 on 2025-09-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_depenses_revenus_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depenses',
            name='date_depense',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depenses',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='depenses',
            name='montant',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='depenses',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='revenus',
            name='montant',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='revenus',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
