# Generated by Django 5.2 on 2025-09-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_depenses_date_depense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depenses',
            name='name',
        ),
        migrations.RemoveField(
            model_name='revenus',
            name='name',
        ),
    ]
