# Generated by Django 5.2 on 2025-09-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_depenses_name_remove_revenus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='depenses',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='revenus',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
