# Generated by Django 5.2 on 2025-09-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_depenses_name_revenus_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
        migrations.AddField(
            model_name='profileblog',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='revenus',
            name='date_revenu',
            field=models.DateField(blank=True, null=True),
        ),
    ]
