# Generated by Django 5.2 on 2025-09-18 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_blog_description_profileblog_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField(verbose_name="Heure d'arrivée")),
                ('is_present', models.BooleanField(default=True, verbose_name='Est présent')),
                ('is_late', models.BooleanField(default=False, verbose_name='Est en retard')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='blog.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-arrival_time'],
            },
        ),
    ]
