# Generated by Django 5.2 on 2025-09-21 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_employe_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depenses',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='blog.blog'),
        ),
        migrations.AlterField(
            model_name='depenses',
            name='date_depense',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='revenus',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenu', to='blog.blog'),
        ),
        migrations.AlterField(
            model_name='revenus',
            name='date_revenu',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Dettes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(null=True)),
                ('date_dettes', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(default='', max_length=25)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dettes', to='blog.blog')),
            ],
        ),
    ]
