# Generated by Django 5.2 on 2025-09-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_depenses_blog_alter_depenses_date_depense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileblog',
            name='type_salon',
            field=models.CharField(blank=True, default='femme', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='booking',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='conseil_beaute',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
