# Generated by Django 5.2 on 2025-09-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_profileblog_type_salon_service_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileblog',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileblog',
            name='commune',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profileblog',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
