# Generated by Django 5.2 on 2025-09-23 15:22

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_profileblog_adresse_profileblog_commune_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprofilblog',
            name='image',
            field=models.ImageField(null=True, upload_to=blog.models.upload_to_unique_uuid_image),
        ),
    ]
