# Generated by Django 5.2 on 2025-09-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_imageprofilblog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dettes',
            name='datte_rembourssement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dettes',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
