# Generated by Django 5.2 on 2025-10-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_catalogue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catalogue',
        ),
    ]
