# Generated by Django 5.2 on 2025-07-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerrestaurant',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='employerrestaurant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='salairerestaurant',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='horaireemployerrestaurant',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='horaireemployerrestaurant',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='revenusrestaurant',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='salairerestaurant',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='stockrestaurant',
            name='blog',
        ),
        migrations.DeleteModel(
            name='DepenseSalon',
        ),
        migrations.DeleteModel(
            name='EmployerRestaurant',
        ),
        migrations.DeleteModel(
            name='HoraireEmployerRestaurant',
        ),
        migrations.DeleteModel(
            name='RevenusRestaurant',
        ),
        migrations.DeleteModel(
            name='SalaireRestaurant',
        ),
        migrations.DeleteModel(
            name='StockRestaurant',
        ),
    ]
