# Generated by Django 5.2 on 2025-07-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='type_compte',
            field=models.CharField(blank=True, default='User', max_length=20),
        ),
    ]
