# Generated by Django 5.2 on 2025-09-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0002_profileuser_type_compte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='pseudo',
        ),
    ]
