# Generated by Django 5.2 on 2025-09-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0004_depenses_dettes_revenus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dettes',
            name='name',
        ),
        migrations.AddField(
            model_name='dettes',
            name='datte_rembourssement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
