# Generated by Django 5.2 on 2025-09-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0005_remove_dettes_name_dettes_datte_rembourssement'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='commune',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='numero_rue',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='rue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
