# Generated by Django 5.2 on 2025-10-29 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0006_profileuser_email_alter_profileuser_commune_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secutity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_publique', models.CharField(blank=True, max_length=500, null=True)),
                ('signature', models.ImageField(upload_to='signature/')),
                ('id_hedera', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_bancaire', models.CharField(blank=True, max_length=255, null=True)),
                ('paiement_mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secutity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
