# Generated by Django 5.2 on 2025-10-31 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0007_secutity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_signe', models.FileField(upload_to='documents_signes/', verbose_name='Document PDF Signé')),
                ('type_document', models.CharField(max_length=100, verbose_name='Type de Document')),
                ('document_hash_sha256', models.CharField(max_length=64, verbose_name='Hash SHA-256 (Ancrage)')),
                ('hedera_timestamp', models.CharField(max_length=255, unique=True, verbose_name='Horodatage Hedera (Consensus Time)')),
                ('hedera_transaction_id', models.CharField(max_length=255, verbose_name='ID de Transaction Hedera')),
                ('lien_verification_hedera', models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien de Vérification Hedera')),
                ('statut', models.CharField(default='SIGNÉ & ANCRÉ', max_length=50, verbose_name='Statut du Document')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('signataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_signes', to=settings.AUTH_USER_MODEL, verbose_name='Signataire')),
            ],
            options={
                'verbose_name': 'Document Signé',
                'verbose_name_plural': 'Documents Signés',
            },
        ),
        migrations.DeleteModel(
            name='Secutity',
        ),
        migrations.AddConstraint(
            model_name='documentsigne',
            constraint=models.UniqueConstraint(fields=('document_hash_sha256',), name='unique_document_hash'),
        ),
    ]
