# Generated by Django 5.2 on 2025-10-31 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0008_documentsigne_delete_secutity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secutity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_publique', models.CharField(blank=True, max_length=500, null=True)),
                ('signature', models.ImageField(upload_to='signature/')),
                ('verification_faciale', models.ImageField(upload_to='image_faciale/')),
                ('id_hedera', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_bancaire', models.CharField(blank=True, max_length=255, null=True)),
                ('paiement_mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secutity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
