# Generated by Django 5.2 on 2025-10-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0009_secutity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secutity',
            name='cle_publique',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='secutity',
            name='verification_faciale',
            field=models.ImageField(blank=True, null=True, upload_to='image_faciale/'),
        ),
    ]
