# Generated by Django 5.2 on 2025-10-31 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0010_alter_secutity_cle_publique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secutity',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security', to=settings.AUTH_USER_MODEL),
        ),
    ]
