# Generated by Django 5.2 on 2025-11-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0011_alter_secutity_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secutity',
            name='cle_publique',
            field=models.FileField(blank=True, null=True, upload_to='certificats_publiques/'),
        ),
    ]
