# Generated by Django 5.2.7 on 2025-11-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0012_alter_secutity_cle_publique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsigne',
            name='hedera_timestamp',
            field=models.CharField(max_length=255, verbose_name='Horodatage Hedera (Consensus Time)'),
        ),
    ]
