# Generated by Django 5.2.7 on 2025-11-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0013_alter_documentsigne_hedera_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsigne',
            name='code',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='documentsigne',
            name='type_document',
            field=models.CharField(max_length=255, verbose_name='Type de Document'),
        ),
    ]
